-- ============================================
-- CrowdVolt Payouts Schema
-- Run this in your Supabase SQL Editor
-- ============================================

-- Add Stripe Connect account ID to profiles
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS stripe_connect_account_id TEXT,
ADD COLUMN IF NOT EXISTS stripe_connect_onboarded BOOLEAN DEFAULT FALSE;

-- Payouts table
CREATE TABLE IF NOT EXISTS payouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  amount NUMERIC(10,2) NOT NULL,
  currency TEXT NOT NULL DEFAULT 'PEN',
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  stripe_transfer_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

ALTER TABLE payouts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Sellers can view their own payouts"
  ON payouts FOR SELECT USING (auth.uid() = seller_id);

CREATE POLICY "System can insert payouts"
  ON payouts FOR INSERT WITH CHECK (auth.uid() = seller_id);

CREATE INDEX IF NOT EXISTS idx_payouts_seller_id ON payouts(seller_id);
