-- CrowdVolt Backend Database Schema
-- Run this in your Supabase SQL editor

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create profiles table
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE,
  full_name TEXT,
  email TEXT,
  phone TEXT,
  stripe_customer_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (id)
);

-- RLS for profiles
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profile"
  ON profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON profiles FOR UPDATE
  USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

-- Trigger to auto-create profile on user registration
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, created_at)
  VALUES (NEW.id, NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Update listings table - add new columns
ALTER TABLE listings
ADD COLUMN IF NOT EXISTS ticket_type TEXT DEFAULT 'ga' CHECK (ticket_type IN ('ga', 'vip')),
ADD COLUMN IF NOT EXISTS ticket_file_path TEXT;

-- Create orders table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT UNIQUE NOT NULL,
  listing_id BIGINT REFERENCES listings(id) ON DELETE CASCADE,
  buyer_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  seller_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  ticket_quantity INT NOT NULL,
  ticket_type TEXT NOT NULL,
  price_per_ticket NUMERIC(10,2) NOT NULL,
  service_fee NUMERIC(10,2) NOT NULL,
  total_amount NUMERIC(10,2) NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'delivered', 'completed', 'cancelled', 'refunded')),
  stripe_payment_intent_id TEXT,
  delivery_email TEXT NOT NULL,
  delivery_phone TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for orders
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Buyers can view their own orders"
  ON orders FOR SELECT
  USING (auth.uid() = buyer_id);

CREATE POLICY "Sellers can view orders for their listings"
  ON orders FOR SELECT
  USING (auth.uid() = seller_id);

CREATE POLICY "System can insert orders"
  ON orders FOR INSERT
  WITH CHECK (true);

CREATE POLICY "System can update orders"
  ON orders FOR UPDATE
  USING (true);

-- Create offers table
CREATE TABLE IF NOT EXISTS offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  buyer_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  ticket_type TEXT NOT NULL,
  price_per_ticket NUMERIC(10,2) NOT NULL,
  quantity INT NOT NULL,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'accepted', 'declined', 'expired', 'cancelled')),
  stripe_payment_intent_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '24 hours')
);

-- RLS for offers
ALTER TABLE offers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Buyers can view their own offers"
  ON offers FOR SELECT
  USING (auth.uid() = buyer_id);

CREATE POLICY "Buyers can create offers"
  ON offers FOR INSERT
  WITH CHECK (auth.uid() = buyer_id);

CREATE POLICY "Buyers can update their own offers"
  ON offers FOR UPDATE
  USING (auth.uid() = buyer_id);

-- Create trigger to update updated_at on orders
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER update_orders_updated_at
    BEFORE UPDATE ON orders
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Function to generate order numbers
CREATE OR REPLACE FUNCTION generate_order_number()
RETURNS TEXT AS $$
DECLARE
    date_part TEXT;
    sequence_part TEXT;
    counter INT;
BEGIN
    -- Get current date in YYYYMMDD format
    date_part := to_char(CURRENT_DATE, 'YYYYMMDD');

    -- Get count of orders created today
    SELECT COUNT(*) + 1 INTO counter
    FROM orders
    WHERE DATE(created_at) = CURRENT_DATE;

    -- Format as 3-digit number
    sequence_part := LPAD(counter::TEXT, 3, '0');

    RETURN 'CV-' || date_part || '-' || sequence_part;
END;
$$ LANGUAGE plpgsql;

-- STORAGE: Create the "ticket-files" bucket manually in Supabase Dashboard:
-- 1. Go to Storage → New Bucket → name: "ticket-files" → PRIVATE (not public)
-- 2. Add policy: allow authenticated users to upload (INSERT)
-- 3. Add policy: allow authenticated users to read their own files (SELECT)