-- Event Requests table
-- Run in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS event_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name TEXT NOT NULL,
  event_link TEXT,
  event_date DATE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE event_requests ENABLE ROW LEVEL SECURITY;

-- Anyone can insert (no auth required for requests)
CREATE POLICY "Anyone can submit event requests"
  ON event_requests FOR INSERT WITH CHECK (true);

-- Only service role can read (admin only)
CREATE POLICY "Service role can read event requests"
  ON event_requests FOR SELECT USING (false);
