-- Referrals system
-- Run in Supabase SQL Editor

-- Track referrals
CREATE TABLE IF NOT EXISTS referrals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  referred_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed')),
  reward_amount NUMERIC(10,2) NOT NULL DEFAULT 15.00,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  UNIQUE(referred_id) -- each user can only be referred once
);

ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own referrals"
  ON referrals FOR SELECT USING (auth.uid() = referrer_id OR auth.uid() = referred_id);

CREATE INDEX IF NOT EXISTS idx_referrals_referrer ON referrals(referrer_id);
CREATE INDEX IF NOT EXISTS idx_referrals_referred ON referrals(referred_id);

-- Add credit balance to profiles
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS credit_balance NUMERIC(10,2) NOT NULL DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS referred_by UUID REFERENCES auth.users(id);

-- Function to increment credit balance
CREATE OR REPLACE FUNCTION increment_credit(user_id UUID, amount NUMERIC)
RETURNS VOID AS $$
BEGIN
  UPDATE profiles
  SET credit_balance = credit_balance + amount
  WHERE id = user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
